//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devSmartTAS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionView
    {
        public string StaffID { get; set; }
        public Nullable<byte> TA { get; set; }
        public Nullable<int> CtrlID { get; set; }
        public Nullable<System.DateTime> FirstIn { get; set; }
        public Nullable<System.DateTime> LastOut { get; set; }
        public string EventID { get; set; }
        public string EventName { get; set; }
        public string Name { get; set; }
        public Nullable<long> UserID { get; set; }
        public string TAWeekID { get; set; }
    }
}
