//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int ID { get; set; }
        public int ProID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime AssignedDateTime { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
        public string FullName { get; set; }
        public Nullable<double> Point { get; set; }
        public string Description { get; set; }
        public string WhoModified { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public Nullable<System.DateTime> DeteledDateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project_Log Project_Log { get; set; }
    }
}
