//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScopeType()
        {
            this.Project_Log = new HashSet<Project_Log>();
        }
    
        public int ScopeTypeId { get; set; }
        public int ScopeId { get; set; }
        public string ScopeTypeDescription { get; set; }
        public Nullable<int> OrderList { get; set; }
        public Nullable<System.DateTime> Unload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Log> Project_Log { get; set; }
        public virtual ScopeOfService ScopeOfService { get; set; }
    }
}
