//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTask
    {
        public int ID { get; set; }
        public int ScopeID { get; set; }
        public string SubTasks { get; set; }
        public Nullable<int> OrderSubTasks { get; set; }
        public Nullable<System.DateTime> UnLoad { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual ScopeOfService ScopeOfService { get; set; }
    }
}
