//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLogView
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string ProjectNo { get; set; }
        public string Name { get; set; }
        public string Parent { get; set; }
        public string ScopeName { get; set; }
        public string Branch { get; set; }
        public string Team { get; set; }
        public string SubTasks { get; set; }
        public System.DateTime WorkedDate { get; set; }
        public double Hours { get; set; }
        public string Description { get; set; }
    }
}
