//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devPMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewApprovedVacationPerDate
    {
        public int EmpId { get; set; }
        public string FullName { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public int RequestType { get; set; }
        public Nullable<double> TotalValue { get; set; }
    }
}
