//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTVN.PMS.Common.myServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myServiceReference.IGeneralService")]
    public interface IGeneralService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetDate", ReplyAction="http://tempuri.org/IGeneralService/GetDateResponse")]
        System.DateTime GetDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetDate", ReplyAction="http://tempuri.org/IGeneralService/GetDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetPicture", ReplyAction="http://tempuri.org/IGeneralService/GetPictureResponse")]
        byte[] GetPicture(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetPicture", ReplyAction="http://tempuri.org/IGeneralService/GetPictureResponse")]
        System.Threading.Tasks.Task<byte[]> GetPictureAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/SendEmail", ReplyAction="http://tempuri.org/IGeneralService/SendEmailResponse")]
        bool SendEmail(string to, string subject, string body, string fromDisplayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/SendEmail", ReplyAction="http://tempuri.org/IGeneralService/SendEmailResponse")]
        System.Threading.Tasks.Task<bool> SendEmailAsync(string to, string subject, string body, string fromDisplayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/SendMail", ReplyAction="http://tempuri.org/IGeneralService/SendMailResponse")]
        bool SendMail(string[] to, string[] cc, string subject, string body, string fromDisplayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/SendMail", ReplyAction="http://tempuri.org/IGeneralService/SendMailResponse")]
        System.Threading.Tasks.Task<bool> SendMailAsync(string[] to, string[] cc, string subject, string body, string fromDisplayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_Submit", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_SubmitResponse")]
        string EmailVacation_Submit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_Submit", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_SubmitResponse")]
        System.Threading.Tasks.Task<string> EmailVacation_SubmitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_SubmitPartial", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_SubmitPartialResponse")]
        string EmailVacation_SubmitPartial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_SubmitPartial", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_SubmitPartialResponse")]
        System.Threading.Tasks.Task<string> EmailVacation_SubmitPartialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequest", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequestResponse")]
        string EmailVacation_ActionOnRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequest", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequestResponse")]
        System.Threading.Tasks.Task<string> EmailVacation_ActionOnRequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequests", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequestsResponse")]
        string EmailVacation_ActionOnRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequests", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_ActionOnRequestsResponse")]
        System.Threading.Tasks.Task<string> EmailVacation_ActionOnRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_DeletePendingRequest", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_DeletePendingRequestResponse")]
        string EmailVacation_DeletePendingRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailVacation_DeletePendingRequest", ReplyAction="http://tempuri.org/IGeneralService/EmailVacation_DeletePendingRequestResponse")]
        System.Threading.Tasks.Task<string> EmailVacation_DeletePendingRequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailProject_Assign", ReplyAction="http://tempuri.org/IGeneralService/EmailProject_AssignResponse")]
        string EmailProject_Assign();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailProject_Assign", ReplyAction="http://tempuri.org/IGeneralService/EmailProject_AssignResponse")]
        System.Threading.Tasks.Task<string> EmailProject_AssignAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailTemplate", ReplyAction="http://tempuri.org/IGeneralService/EmailTemplateResponse")]
        string EmailTemplate(string templateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/EmailTemplate", ReplyAction="http://tempuri.org/IGeneralService/EmailTemplateResponse")]
        System.Threading.Tasks.Task<string> EmailTemplateAsync(string templateName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralServiceChannel : SSTVN.PMS.Common.myServiceReference.IGeneralService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralServiceClient : System.ServiceModel.ClientBase<SSTVN.PMS.Common.myServiceReference.IGeneralService>, SSTVN.PMS.Common.myServiceReference.IGeneralService {
        
        public GeneralServiceClient() {
        }
        
        public GeneralServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetDate() {
            return base.Channel.GetDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDateAsync() {
            return base.Channel.GetDateAsync();
        }
        
        public byte[] GetPicture(string fileName) {
            return base.Channel.GetPicture(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPictureAsync(string fileName) {
            return base.Channel.GetPictureAsync(fileName);
        }
        
        public bool SendEmail(string to, string subject, string body, string fromDisplayName) {
            return base.Channel.SendEmail(to, subject, body, fromDisplayName);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailAsync(string to, string subject, string body, string fromDisplayName) {
            return base.Channel.SendEmailAsync(to, subject, body, fromDisplayName);
        }
        
        public bool SendMail(string[] to, string[] cc, string subject, string body, string fromDisplayName) {
            return base.Channel.SendMail(to, cc, subject, body, fromDisplayName);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailAsync(string[] to, string[] cc, string subject, string body, string fromDisplayName) {
            return base.Channel.SendMailAsync(to, cc, subject, body, fromDisplayName);
        }
        
        public string EmailVacation_Submit() {
            return base.Channel.EmailVacation_Submit();
        }
        
        public System.Threading.Tasks.Task<string> EmailVacation_SubmitAsync() {
            return base.Channel.EmailVacation_SubmitAsync();
        }
        
        public string EmailVacation_SubmitPartial() {
            return base.Channel.EmailVacation_SubmitPartial();
        }
        
        public System.Threading.Tasks.Task<string> EmailVacation_SubmitPartialAsync() {
            return base.Channel.EmailVacation_SubmitPartialAsync();
        }
        
        public string EmailVacation_ActionOnRequest() {
            return base.Channel.EmailVacation_ActionOnRequest();
        }
        
        public System.Threading.Tasks.Task<string> EmailVacation_ActionOnRequestAsync() {
            return base.Channel.EmailVacation_ActionOnRequestAsync();
        }
        
        public string EmailVacation_ActionOnRequests() {
            return base.Channel.EmailVacation_ActionOnRequests();
        }
        
        public System.Threading.Tasks.Task<string> EmailVacation_ActionOnRequestsAsync() {
            return base.Channel.EmailVacation_ActionOnRequestsAsync();
        }
        
        public string EmailVacation_DeletePendingRequest() {
            return base.Channel.EmailVacation_DeletePendingRequest();
        }
        
        public System.Threading.Tasks.Task<string> EmailVacation_DeletePendingRequestAsync() {
            return base.Channel.EmailVacation_DeletePendingRequestAsync();
        }
        
        public string EmailProject_Assign() {
            return base.Channel.EmailProject_Assign();
        }
        
        public System.Threading.Tasks.Task<string> EmailProject_AssignAsync() {
            return base.Channel.EmailProject_AssignAsync();
        }
        
        public string EmailTemplate(string templateName) {
            return base.Channel.EmailTemplate(templateName);
        }
        
        public System.Threading.Tasks.Task<string> EmailTemplateAsync(string templateName) {
            return base.Channel.EmailTemplateAsync(templateName);
        }
    }
}
