//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devForum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public int EmployeeID { get; set; }
        public int TeamID { get; set; }
        public int Permission { get; set; }
        public string Position { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<System.DateTime> TerminatedDateTime { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
        public Nullable<int> RealEmployeeId { get; set; }
    }
}
