//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devForum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reply()
        {
            this.ReplyLikes = new HashSet<ReplyLike>();
        }
    
        public int ReplyId { get; set; }
        public int ThreadId { get; set; }
        public int CommentId { get; set; }
        public Nullable<int> ParentReplyId { get; set; }
        public int UserId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public Nullable<System.DateTime> DeletedDT { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Thread Thread { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyLike> ReplyLikes { get; set; }
    }
}
